name: Build movie service

on:
  push:
    branches:
      - dev/release-test

jobs:

  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t "${{ secrets.DOCKERHUB_USER }}/mm-movie-service:latest" .
          docker push "${{ secrets.DOCKERHUB_USER }}/mm-movie-service:latest"
